app:
  build: .
  command: bash -c "(bundle check || bundle install) && (rake db:exists && rake db:migrate || rake db:create db:migrate db:seed) && rm -f tmp/pids/server.pid && rails server -p 3000 -b '0.0.0.0'"
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
postgres:
  image: postgres:9.4
  ports:
    - "5432"